/**
 * lib/dodoLinks.ts
 * Single source of truth for all Dodo Payments checkout URLs.
 * All 49 products now have real product IDs.
 */
export const dodoLinks: Record<string, string> = {
  "daily-task-checklist":                    "https://checkout.dodopayments.com/buy/pdt_0Ngi4wGYjQzH5HPJkp59c?quantity=1",
  "weekly-goal-planner":                     "https://checkout.dodopayments.com/buy/pdt_0Ngi59ZfPZ7YNw8BeRILe?quantity=1",
  "business-card-copy-template":             "https://checkout.dodopayments.com/buy/pdt_0Ngi5EnBBUPq3MGNFtWzF?quantity=1",
  "instagram-bio-template-pack":             "https://checkout.dodopayments.com/buy/pdt_0Ngi5X1hlKZJO5SNbXvoj?quantity=1",
  "password-manager-sheet":                  "https://checkout.dodopayments.com/buy/pdt_0Ngi5f9Rh3W1Wpozwqnoe?quantity=1",
  "meeting-agenda-template":                 "https://checkout.dodopayments.com/buy/pdt_0Ngi5n3usHLGWQlKM4UyH?quantity=1",
  "invoice-template-pack":                   "https://checkout.dodopayments.com/buy/pdt_0Ngi5z3fL7DhNCVf9ekdz?quantity=1",
  "blog-post-outline-template":              "https://checkout.dodopayments.com/buy/pdt_0Ngi66iKfIsNBNpt4S5iX?quantity=1",
  "cold-email-template-pack":                "https://checkout.dodopayments.com/buy/pdt_0Ngi6I52ap13pPUQKET0O?quantity=1",
  "social-media-bio-kit":                    "https://checkout.dodopayments.com/buy/pdt_0Ngi6NXuyZ6CphyFdAmff?quantity=1",
  "youtube-description-template-pack":       "https://checkout.dodopayments.com/buy/pdt_0Ngi6VFbhILWycSbTlvEe?quantity=1",
  "small-business-legal-checklist":          "https://checkout.dodopayments.com/buy/pdt_0Ngi6bhFcxSeXR0sUFZRb?quantity=1",
  "client-welcome-email-template":           "https://checkout.dodopayments.com/buy/pdt_0Ngi6iFh7x3EBeRVbskTQ?quantity=1",
  "brand-color-palette-planner":             "https://checkout.dodopayments.com/buy/pdt_0Ngi6uErIq1OBmKQGr6YW?quantity=1",
  "website-copywriting-guide":               "https://checkout.dodopayments.com/buy/pdt_0Ngi6zx2aRiilgyJJjfQG?quantity=1",
  "30-day-content-plan-template":            "https://checkout.dodopayments.com/buy/pdt_0Ngi75E4dfncK7VsCQ7NU?quantity=1",
  "facebook-page-setup-checklist":           "https://checkout.dodopayments.com/buy/pdt_0Ngi7Bc2QrGYPL1yi8Vs9?quantity=1",
  "email-signature-template-pack":           "https://checkout.dodopayments.com/buy/pdt_0Ngi7MpPemNvCeCavyjIa?quantity=1",
  "business-budget-tracker":                 "https://checkout.dodopayments.com/buy/pdt_0Ngi7iO6mQ4INjppPTjNS?quantity=1",
  "google-business-profile-setup-guide":     "https://checkout.dodopayments.com/buy/pdt_0Ngi7oUPrnXbGwED3LpdV?quantity=1",
  "customer-feedback-form-template":         "https://checkout.dodopayments.com/buy/pdt_0Ngi7v6xCRSv017G9EJDg?quantity=1",
  "linkedin-profile-optimization-guide":     "https://checkout.dodopayments.com/buy/pdt_0Ngi83uM4R23banHc49A8?quantity=1",
  "small-business-tax-prep-checklist":       "https://checkout.dodopayments.com/buy/pdt_0Ngi88b16UUGjy2wSxxPR?quantity=1",
  "digital-product-pricing-guide":           "https://checkout.dodopayments.com/buy/pdt_0Ngi8CYiODS2VWnKtdO2Z?quantity=1",
  "website-launch-checklist":                "https://checkout.dodopayments.com/buy/pdt_0Ngi8I0gsgKLLqo2TcAEj?quantity=1",
  "content-repurposing-guide":               "https://checkout.dodopayments.com/buy/pdt_0Ngi8Nvtktf2kgqx2gopY?quantity=1",
  "remote-work-productivity-planner":        "https://checkout.dodopayments.com/buy/pdt_0Ngi8S6ybNdIFrQEHLX1q?quantity=1",
  "small-business-grant-checklist":          "https://checkout.dodopayments.com/buy/pdt_0Ngi8WrFwruBtT5C7Xvcv?quantity=1",
  "social-media-audit-template":             "https://checkout.dodopayments.com/buy/pdt_0Ngi8bmXXV7zGioamcY8S?quantity=1",
  "email-marketing-starter-kit":             "https://checkout.dodopayments.com/buy/pdt_0Ngi8ft5KvIhIRwhnw2gz?quantity=1",
  "freelance-contract-template-pack":        "https://checkout.dodopayments.com/buy/pdt_0Ngi8lBNwX8cruXTpdYOP?quantity=1",
  "product-launch-planning-kit":             "https://checkout.dodopayments.com/buy/pdt_0Ngi8q0c4CStdCNi0y6iX?quantity=1",
  "small-business-seo-checklist":            "https://checkout.dodopayments.com/buy/pdt_0Ngi8w9Kl48lQfOQY39aa?quantity=1",
  "customer-onboarding-template-pack":       "https://checkout.dodopayments.com/buy/pdt_0Ngi90Ndl9kMROPQUDsNi?quantity=1",
  "social-media-content-calendar-template":  "https://checkout.dodopayments.com/buy/pdt_0Ngi96FoWaDaPf4uT28Xh?quantity=1",
  "freelance-proposal-template-pack":        "https://checkout.dodopayments.com/buy/pdt_0Ngi9BgMclH4YlXejfp8K?quantity=1",
  "business-plan-template-kit":              "https://checkout.dodopayments.com/buy/pdt_0Ngi9Gcx1x1wj3IUrLxdY?quantity=1",
  "internet-setup-guide":                    "https://checkout.dodopayments.com/buy/pdt_0Ngi9RAWCNAtl69UeVEuw?quantity=1",
  "remote-team-communication-playbook":      "https://checkout.dodopayments.com/buy/pdt_0Ngi9ey6Nv1dzdeDFsz2a?quantity=1",
  "brand-identity-starter-kit":              "https://checkout.dodopayments.com/buy/pdt_0Ngi9lxjI3xjJIpGwz7hr?quantity=1",
  "digital-branding-starter-kit":            "https://checkout.dodopayments.com/buy/pdt_0Ngi9sn9tUiTGI330Vz8S?quantity=1",
  "business-financial-planning-spreadsheet": "https://checkout.dodopayments.com/buy/pdt_0NgiA1YVsJKpFvI8vRXY8?quantity=1",
  "small-business-automation-template-kit":  "https://checkout.dodopayments.com/buy/pdt_0NgiA8LGHvEHRf5mHVDAe?quantity=1",
  "complete-marketing-template-bundle":      "https://checkout.dodopayments.com/buy/pdt_0NgiAG8m7qDUiIvpY1bjs?quantity=1",
  "ecommerce-store-launch-kit":              "https://checkout.dodopayments.com/buy/pdt_0NgiAMy8AtJaCBJnzY5tc?quantity=1",
  "saas-landing-page-template-kit":          "https://checkout.dodopayments.com/buy/pdt_0NgiASCsDz1g1Hkcx6Kdr?quantity=1",
  "business-website-starter-template":       "https://checkout.dodopayments.com/buy/pdt_0NgiAYB4wakJntE6sJbkJ?quantity=1",
  "complete-small-business-starter-bundle":  "https://checkout.dodopayments.com/buy/pdt_0NgiAh6GbGNSHzL6Y3FlA?quantity=1",
  "ultimate-digital-business-kit":           "https://checkout.dodopayments.com/buy/pdt_0NgiAnOKjF5ISLiHrWOFd?quantity=1",
};
