/**
 * lib/paddleLinks.ts — Maps product slug → Paddle price ID
 * Used with Paddle.js Checkout.open() instead of direct URLs.
 */
export const paddleLinks: Record<string, string> = {
  "daily-task-checklist"                          : "pri_01kxapds05aq7tzt45wa5cncyr",
  "weekly-goal-planner"                           : "pri_01kxapdtatxtzkyk4jnkc71cay",
  "business-card-copy-template"                   : "pri_01kxapdv7z603jvshp62e6j9qj",
  "instagram-bio-template-pack"                   : "pri_01kxapdw4qvzmrs85bfp5fam77",
  "password-manager-sheet"                        : "pri_01kxapdx1zw3aqcjtpn497r1ce",
  "meeting-agenda-template"                       : "pri_01kxapdxyg8gj1pz04b9qfsepn",
  "invoice-template-pack"                         : "pri_01kxapdywvbz7ypdr0twq0wn0d",
  "blog-post-outline-template"                    : "pri_01kxapdzv48fk1a0arg0m8akr1",
  "cold-email-template-pack"                      : "pri_01kxape0p4gak56jcvwbnz6sbj",
  "social-media-bio-kit"                          : "pri_01kxape1nfj96h9633xpjan5va",
  "youtube-description-template-pack"             : "pri_01kxape2v1hb807sakwch7c4rd",
  "small-business-legal-checklist"                : "pri_01kxape3svass201faq4dphjty",
  "client-welcome-email-template"                 : "pri_01kxape4rc8x5f4rkh5dvgxph6",
  "brand-color-palette-planner"                   : "pri_01kxape5mp5xejshrsm76eqwy4",
  "website-copywriting-guide"                     : "pri_01kxape6mmr16tt7jes5hpc8kp",
  "30-day-content-plan-template"                  : "pri_01kxape7hn5zxe65dpkb4wbpay",
  "facebook-page-setup-checklist"                 : "pri_01kxape8chabyp1k4hh9sc49m6",
  "email-signature-template-pack"                 : "pri_01kxape97xv1z1syqkf4qp6ztp",
  "business-budget-tracker"                       : "pri_01kxapea5dh33xdjrvna52987f",
  "google-business-profile-setup-guide"           : "pri_01kxapeb1m2421xxsf2gatp5wp",
  "customer-feedback-form-template"               : "pri_01kxapec1dt64fdka6rrfphg1m",
  "linkedin-profile-optimization-guide"           : "pri_01kxapecyf8ex1gr4p08kggae7",
  "small-business-tax-prep-checklist"             : "pri_01kxapedskv6gjw188hk3sg3v4",
  "digital-product-pricing-guide"                 : "pri_01kxapeepkfg0b96rsg8w4k2ed",
  "website-launch-checklist"                      : "pri_01kxapefhemp2j4ytmbzjcmdpx",
  "content-repurposing-guide"                     : "pri_01kxapegbetkn6qzxzd2thawy6",
  "remote-work-productivity-planner"              : "pri_01kxapeh8256edv56v3b6qcyk2",
  "small-business-grant-checklist"                : "pri_01kxapej4ngxdwgbejxygjnt1x",
  "social-media-audit-template"                   : "pri_01kxapejz8t6pz247emhnn7g5v",
  "email-marketing-starter-kit"                   : "pri_01kxapekwrf9wkcxq6qs3z2zgh",
  "freelance-contract-template-pack"              : "pri_01kxapemt0xfza8s7vk0pvyz7t",
  "product-launch-planning-kit"                   : "pri_01kxapenqz2rx8149pd5yb63y8",
  "small-business-seo-checklist"                  : "pri_01kxapepr1qd1q3pnz3ts2bm8b",
  "customer-onboarding-template-pack"             : "pri_01kxapeqp2zht9y4983m0r26js",
  "social-media-content-calendar-template"        : "pri_01kxaperqfxqdb5kfmhq0dxd3s",
  "freelance-proposal-template-pack"              : "pri_01kxapesjqn0msj29cext4xrvs",
  "business-plan-template-kit"                    : "pri_01kxapetkn1kwvxk8eejdzknpm",
  "internet-setup-guide"                          : "pri_01kxapevfha7hnh2mcemzec3y5",
  "remote-team-communication-playbook"            : "pri_01kxapewaqa9xdt7e9g9a5a28y",
  "brand-identity-starter-kit"                    : "pri_01kxapex9ypjabzgwdbfd16r74",
  "digital-branding-starter-kit"                  : "pri_01kxapey4s6saxj0yx45rtyzhf",
  "business-financial-planning-spreadsheet"       : "pri_01kxapez05sbtdq2y6fszbgxxq",
  "small-business-automation-template-kit"        : "pri_01kxapezxf3y8png6dhtbvzn8x",
  "complete-marketing-template-bundle"            : "pri_01kxapf0x4agyez2165mksrdjr",
  "ecommerce-store-launch-kit"                    : "pri_01kxapf1qy5758txmxz0qgpdnd",
  "saas-landing-page-template-kit"                : "pri_01kxapf2jkn9b53v1x85m1gcwg",
  "business-website-starter-template"             : "pri_01kxapf3gq0c5dnag0z2jwtz85",
  "complete-small-business-starter-bundle"        : "pri_01kxapf4fyvsmnzp20vfvr030e",
  "ultimate-digital-business-kit"                 : "pri_01kxapf59zjf1a0rhwarcxctra",
};
