#!/usr/bin/env node
/**
 * scripts/polar-setup.mjs
 *
 * One-time setup script (mirrors the old paddle-setup.mjs referenced in
 * lib/paddleProductMap.ts). Reads data/products.ts, creates a matching
 * one-time-purchase product on Polar for every entry, then writes
 * lib/polarProductIds.ts with the resulting slug -> Polar product ID map.
 *
 * Usage:
 *   POLAR_ACCESS_TOKEN=polar_oat_xxx node scripts/polar-setup.mjs
 *
 * Requires an Organization Access Token (Polar Dashboard -> Settings ->
 * Developers -> Access Tokens) so no organization ID needs to be passed.
 * Pass POLAR_SERVER=sandbox to run against sandbox-api.polar.sh instead.
 *
 * Safe to re-run: it skips any slug that already has an ID in
 * lib/polarProductIds.ts.
 */
import { Polar } from "@polar-sh/sdk";
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const accessToken = process.env.POLAR_ACCESS_TOKEN;
if (!accessToken) {
  console.error("Missing POLAR_ACCESS_TOKEN environment variable.");
  process.exit(1);
}

const server = process.env.POLAR_SERVER === "sandbox" ? "sandbox" : "production";
const polar = new Polar({ accessToken, server });

const productsPath = path.join(__dirname, "../data/products.ts");
const idsPath = path.join(__dirname, "../lib/polarProductIds.ts");

const productsSource = readFileSync(productsPath, "utf8");
const productPattern = /slug:\s*"([^"]+)",\s*name:\s*"([^"]+)",\s*price:\s*([\d.]+)/g;

const products = [];
let match;
while ((match = productPattern.exec(productsSource)) !== null) {
  products.push({ slug: match[1], name: match[2], price: Number(match[3]) });
}

if (products.length === 0) {
  console.error("No products parsed from data/products.ts — aborting.");
  process.exit(1);
}

const existingIdsSource = readFileSync(idsPath, "utf8");
const existingIds = {};
const existingPattern = /"([^"]+)":\s*"([^"]+)"/g;
while ((match = existingPattern.exec(existingIdsSource)) !== null) {
  existingIds[match[1]] = match[2];
}

console.log(`Found ${products.length} products in data/products.ts.`);
console.log(`Creating missing products on Polar (${server})...\n`);

const idMap = { ...existingIds };

for (const product of products) {
  if (idMap[product.slug]) {
    console.log(`⏭️  ${product.slug} — already has an ID, skipping`);
    continue;
  }

  try {
    const created = await polar.products.create({
      name: product.name,
      description: product.name,
      prices: [
        {
          amountType: "fixed",
          priceAmount: Math.round(product.price * 100),
          priceCurrency: "usd",
        },
      ],
    });
    idMap[product.slug] = created.id;
    console.log(`✅ ${product.slug} -> ${created.id}`);
  } catch (err) {
    console.error(`❌ Failed to create "${product.slug}":`, err?.message ?? err);
  }
}

const orderedSlugs = products.map((p) => p.slug).filter((slug) => idMap[slug]);
const lines = orderedSlugs
  .map((slug) => `  "${slug}": "${idMap[slug]}",`)
  .join("\n");

const fileContent = `/**
 * lib/polarProductIds.ts — AUTO-GENERATED by scripts/polar-setup.mjs
 * Maps product slug -> Polar product ID.
 */
export const polarProductIds: Record<string, string> = {
${lines}
};
`;

writeFileSync(idsPath, fileContent, "utf8");
console.log(`\nWrote ${orderedSlugs.length}/${products.length} product IDs to lib/polarProductIds.ts`);

if (orderedSlugs.length < products.length) {
  console.warn("Some products failed to create — re-run the script to retry them.");
  process.exit(1);
}
